ALLOWED_EXTENSIONS = {'xlsx', 'xls'}
MAX_CONTENT_LENGTH = 64 * 1024 * 1024

DB_TABLE_NAME = 'aluminum_pricing'
DB_CODE_COLUMN = '工程编码'
DB_SPEC_COLUMN = '规格说明\n(mm)/(米)'
API_SPEC_COLUMN = '规格说明(mm)/(米)'
DB_NAME_COLUMN = '工程品名'
DB_NAME_KO_COLUMN = '工程品名--韩语'
DB_NAME_EN_COLUMN = '工程品名--英语'
DB_NAME_JA_COLUMN = '工程品名--日语'
DB_NAME_FR_COLUMN = '工程品名--法语'
DB_NAME_ES_COLUMN = '工程品名--西班牙语'

GROUP_NAME_COLUMN_MAP = {
    '韩语组': DB_NAME_KO_COLUMN,
    '英语组': DB_NAME_EN_COLUMN,
    '日语组': DB_NAME_JA_COLUMN,
    '管理员': DB_NAME_KO_COLUMN,
}
DB_UNIT_COLUMN = '计价单位'
DB_PRICE_COLUMN = '10u小氧化(美元)--组装'
DB_PRICE_COLUMN_EN = '10u大氧化(美元)--组装'
DB_PRICE_COLUMN_EN_RMB = '10u大氧化(RMB)--组装'
DB_PRICE_COLUMN_EN_EUR = '10u大氧化(欧元)--组装'
DB_PRICE_COLUMN_RMB = '10u小氧化(RMB)--组装'
DB_PRICE_COLUMN_15U = '15u小氧化(美元)--组装'
DB_PRICE_COLUMN_18U = '18u小氧化(美元)--组装'
DB_IMAGE_COLUMN = '图片'
DB_IMAGE_BASE64_COLUMN = '图片_base64'
DB_CODE_ATTRIBUTE_COLUMN = '编码属性'
DB_ATTRIBUTE_COLUMN = '属性'
DB_WEIGHT_COLUMN = '重量'
DB_PRICING_ATTRIBUTE_COLUMN = '定价属性'

DB_PILE_15_18UM_TABLE = '15_18um_price'
DB_PILE_15_18UM_CODE_COLUMN = '产品编号'
DB_PILE_15_18UM_PRICE_USD = '单价：美元'
DB_PILE_15_18UM_PRICE_EUR = '单价：欧元'
DB_PILE_15_18UM_PRICE_RMB = '单价：人民币'

ALUMINUM_CHANGE_REQUEST_TABLE = 'aluminum_change_requests'
CHANGE_ACTION_CREATE = 'create'
CHANGE_ACTION_UPDATE = 'update'
CHANGE_ACTION_DELETE = 'delete'
CHANGE_ACTION_IMPORT_IMAGES = 'import_images'
CHANGE_ACTION_BATCH_UPDATE_PRICES = 'batch_update_prices'
CHANGE_ACTION_BATCH_UPDATE_DATA = 'batch_update_data'
CHANGE_ACTIONS = (
    CHANGE_ACTION_CREATE,
    CHANGE_ACTION_UPDATE,
    CHANGE_ACTION_DELETE,
    CHANGE_ACTION_IMPORT_IMAGES,
    CHANGE_ACTION_BATCH_UPDATE_PRICES,
    CHANGE_ACTION_BATCH_UPDATE_DATA,
)
CHANGE_STATUS_PENDING = 'pending'
CHANGE_STATUS_APPROVED = 'approved'
CHANGE_STATUS_REJECTED = 'rejected'
CHANGE_STATUS_WITHDRAWN = 'withdrawn'
CHANGE_STATUSES = (
    CHANGE_STATUS_PENDING,
    CHANGE_STATUS_APPROVED,
    CHANGE_STATUS_REJECTED,
    CHANGE_STATUS_WITHDRAWN,
)

API_TO_DB_FIELD_MAP = {
    API_SPEC_COLUMN: DB_SPEC_COLUMN,
}

DB_TO_API_FIELD_MAP = {
    DB_SPEC_COLUMN: API_SPEC_COLUMN,
}

DB_MATERIAL_COLUMN = '材质'

ALUMINUM_LIST_COLUMNS = (
    (DB_CODE_COLUMN, DB_CODE_COLUMN),
    (DB_NAME_COLUMN, DB_NAME_COLUMN),
    (DB_PRICE_COLUMN, DB_PRICE_COLUMN),
    (DB_WEIGHT_COLUMN, DB_WEIGHT_COLUMN),
    (DB_IMAGE_COLUMN, DB_IMAGE_COLUMN),
    (DB_IMAGE_BASE64_COLUMN, DB_IMAGE_BASE64_COLUMN),
    (DB_MATERIAL_COLUMN, DB_MATERIAL_COLUMN),
)
